name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: aliyun3364876459
        password: sby19991105
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://nvidia/cuda:12.2.0-base-ubuntu20.04 docker://registry.cn-hangzhou.aliyuncs.com/onnx_test/nvidia-cuda:12.2.0-base-ubuntu20.04
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称 作者：全栈工程师修炼指南 https://www.bilibili.com/read/cv35192993/?from=search&spm_id_from=333.337.0.0 出处：bilibili
